experiment_name: "Analyse_Referencement_Sources_2024"

duration_days: 1
iterations_per_query: 5
delay_between_iterations_seconds: 5
randomize_query_order: true
use_different_sessions: true
database_url: "sqlite:///experiment_results/experiment_data.db"

models:
  - name: "GPT-4o"
    type: "llm"
    client: "openai"
    enabled: true
    api_key_env_var: "OPENAI_API_KEY"
    parameters:
      model_name: "gpt-4o"
      temperature: 0.7
      max_tokens: 4000

  - name: "Claude-3-Sonnet"
    type: "llm"
    client: "claude"
    enabled: true
    api_key_env_var: "ANTHROPIC_API_KEY"
    parameters:
      model_name: "claude-3-sonnet-20240229"
      temperature: 0.7
      max_tokens: 4000

  - name: "Google-Search"
    type: "search_engine"
    client: "google_search"
    enabled: true
    api_key_env_var: "GOOGLE_API_KEY"
    search_engine_id_env_var: "GOOGLE_CX"
    parameters:
      num_results: 10

queries:
  - id: "info_sante_001"
    text: "Quels sont les symptômes et les traitements de la grippe saisonnière ?"
    category: "Informationnelle - Santé"
    metadata: { "complexité": "faible", "domaine": "santé" }

  - id: "info_tech_001"
    text: "Explique le fonctionnement des transformeurs dans les modèles de langage comme GPT."
    category: "Informationnelle - Technique"
    metadata: { "complexité": "élevée", "domaine": "technologie" }

  - id: "transac_voyage_001"
    text: "Trouver les meilleurs hôtels à Rome pour un week-end en octobre avec un budget de 500 euros."
    category: "Transactionnelle - Voyage"
    metadata: { "intention": "réservation", "domaine": "tourisme" }