experiment_name: "Analyse_Referencement_Sources_2024"

duration_days: 1
iterations_per_query: 1
delay_between_iterations_seconds: 5
randomize_query_order: true
use_different_sessions: true
database_url: "sqlite:///experiment_results/experiment_data.db"

models:
  - name: "GPT-4o"
    type: "llm"
    client: "openai"
    enabled: true
    api_key_env_var: "OPENAI_API_KEY"
    parameters:
      model_name: "gpt-4o"
      temperature: 0.7
      max_tokens: 4000

  - name: "Claude-3-Sonnet"
    type: "llm"
    client: "claude"
    enabled: true
    api_key_env_var: "ANTHROPIC_API_KEY"
    parameters:
      model_name: "claude-3-5-sonnet-20241022"
      temperature: 0.7
      max_tokens: 4000

  - name: "Google-Search"
    type: "search_engine"
    client: "google_search"
    enabled: true
    api_key_env_var: "GOOGLE_API_KEY"
    search_engine_id_env_var: "GOOGLE_CX"
    parameters:
      num_results: 10

  - name: "Bing-Search"
    type: "search_engine"
    client: "bing_search"
    enabled: false  # Désactivé par défaut - activez après avoir obtenu une clé API
    api_key_env_var: "BING_API_KEY"
    parameters:
      num_results: 10

  - name: "Gemini-Pro"
    type: "llm"
    client: "gemini"
    enabled: true
    api_key_env_var: "GEMINI_API_KEY"
    parameters:
      model_name: "gemini-1.5-flash"
      temperature: 0.7
      max_tokens: 4000

  - name: "Perplexity-Online"
    type: "llm"
    client: "perplexity"
    enabled: true
    api_key_env_var: "PERPLEXITY_API_KEY"
    parameters:
      model_name: "sonar"  # Modèle avec recherche web intégrée
      temperature: 0.7
      max_tokens: 4000
      search_recency_filter: "week"  # Filtre pour les résultats récents

# Les requêtes seront chargées depuis un fichier externe